import { z } from 'zod';

export const signupSchema = z.object({
    body: z.object({
        email: z.string().email('Invalid email address'),
        password: z.string().min(8, 'Password must be at least 8 characters long'),
        salt: z.string().optional() // Salt generated by client
    })
});

export const loginSchema = z.object({
    body: z.object({
        email: z.string().email('Invalid email address'),
        password: z.string().min(1, 'Password is required')
    })
});

export const vaultEntrySchema = z.object({
    body: z.object({
        site: z.string().min(1, 'Site is required'),
        username: z.string().min(1, 'Username is required'),
        password: z.string().min(1, 'Password/Encrypted Content is required'),
        iv: z.string().optional(), // Mandatory for Phase 2
        notes: z.string().optional(),
        favorite: z.boolean().optional()
    })
});

