import { z } from 'zod';

export const signupSchema = z.object({
    body: z.object({
        email: z.string().email('Invalid email address'),
        password: z.string().min(8, 'Password must be at least 8 characters long'),
        salt: z.string().optional() // Salt generated by client
    })
});

export const loginSchema = z.object({
    body: z.object({
        email: z.string().email('Invalid email address'),
        password: z.string().min(1, 'Password is required')
    })
});

export const vaultEntrySchema = z.object({
    body: z.object({
        encryptedData: z.string().min(1, 'Encrypted data blob is required'),
        iv: z.string().min(1, 'Encryption IV is required'),
        salt: z.string().min(1, 'Encryption salt is required'),
        version: z.number().optional(),
        favorite: z.boolean().optional()
    })
});


